# Generated by Django 6.0.1 on 2026-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='best_time_to_buy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='deal_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
