# Generated by Django 5.0.1 on 2026-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_platform_remove_product_best_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
