# Generated by Django 5.0.1 on 2026-01-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
