# Generated by Django 5.0.1 on 2026-01-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_productlisting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
